# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TUBITAK-4006-SAL
DESTDIR = ../x64/Debug
QT += core gui widgets
CONFIG += debug
DEFINES += _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64 QT_DLL QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/$(ConfigurationName)
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
    ./TUBITAK4006SAL.h
SOURCES += ./main.cpp \
    ./TUBITAK4006SAL.cpp
FORMS += ./girisEkrani.ui \
    ./okul.ui \
    ./projeEkran1.ui \
    ./picture-screen.ui
RESOURCES += TUBITAK4006SAL.qrc \
    veriler.qrc

HEADERS += \
    TUBITAK4006SAL.h \
    Kaynak_Dosyalar/namespace.h \
    Kaynak_Dosyalar/veriler/veriler1.h \
    Kaynak_Dosyalar/veriler/veriler2.h \
    Kaynak_Dosyalar/veriler/veriler3.h \
    Kaynak_Dosyalar/veriler/veriler18.h \
    Kaynak_Dosyalar/veriler/veriler21.h \
    Kaynak_Dosyalar/veriler/veriler4.h \
    Kaynak_Dosyalar/veriler/veriler5.h \
    Kaynak_Dosyalar/veriler/veriler6.h \
    Kaynak_Dosyalar/veriler/veriler7.h \
    Kaynak_Dosyalar/veriler/veriler8.h \
    Kaynak_Dosyalar/veriler/veriler9.h \
    Kaynak_Dosyalar/veriler/veriler10.h \
    Kaynak_Dosyalar/veriler/veriler11.h \
    Kaynak_Dosyalar/veriler/veriler12.h \
    Kaynak_Dosyalar/veriler/veriler13.h \
    Kaynak_Dosyalar/veriler/veriler14.h \
    Kaynak_Dosyalar/veriler/veriler15.h \
    Kaynak_Dosyalar/veriler/veriler16.h \
    Kaynak_Dosyalar/veriler/veriler17.h \
    Kaynak_Dosyalar/veriler/veriler19.h \
    Kaynak_Dosyalar/veriler/veriler20.h \
    Kaynak_Dosyalar/veriler/veriler22.h \
    Kaynak_Dosyalar/veriler/veriler23.h \
    Kaynak_Dosyalar/veriler/veriler24.h
