#include "namespace.h"

using namespace TUBITAK;

class proje11 {
    public:
    string baslik11;
    string materyaller11;
    string yontemler11;
    string ozet11;
    string amac11;
    string projenin_yonetimi11;
    string sonuclar11;
    string oneriler11;

    proje11() {
    baslik11 = "İLERİ DÜŞÜN GERİ DÖNÜŞTÜR\n";
    materyaller11 = "Türkiye genelinde yapılan geri dönüşüm duyarlılığı anketleri incelendi.\n Bu anketlerden soru örnekleri alınarak yeni bir anket oluşturuldu.\n Ardından okul genelinde her sınıfta beş kız beş erkek öğrenci seçilerek öğrenci seçilerek uygulandı.\n";
    yontemler11 = "Daha önceden Türkiye genelinde yapılmış olan anketler incelendi ve bilinen geri dönüşüm metodları araştırıldı.\n Sonrasında okulum öğrencilerinin okul içinde ve özel yaşamlarında hangi geri dönüşüm metodlarını ne oranda kullanılabildiği araştırıldı.\n Yaptığım anketler ile kadın ve erkek öğrencilerin geri dönüşümün ne kadar içinde olduklarını tespit etmeye çalıştık.\n";
    ozet11 = "Geri dönüşüm kullanım dışım kalan geri dönüştürülebilir atık malzemelerin çeşitli geri dönüşüm yöntemleri ile ham madde olarak tekrar imalat süreçlerinde kazandırılmasıdır.\n Geri dönüşüm atıklarının nasıl değerlendiğini çevremizdeki insanlar biliyor mu?\n Bu kazandırılma ülke ekonomisine ne kadar katkı sağlıyor?\n Ülke ekonomisi yanında insan yaşamı ve çevre içinde önemi nedir?\n Atıkların hepsini aynı yerde toplamak, ayrışmadan hepsini bir yerde biriktirmekle doğaya ve ülke ekonomisine zarar verdiğimizin farkında mıyız?\n Biz bu konuyu araştırarak, daha önce yapılmış anket ve istatistiksel verilerden yararlanarak insanları bilinçlendirmeyi amaçlıyoruz.\n Sokaklarda çeşitli anketler yaparak her yaş aralığındaki insanların geri dönüşümün ekonomi ve birçok konu için ne kadar faydalı olduğu konusunda farkındalık yaratmak istiyoruz.\n";
    amac11 = "Geri dönüşümün gelişmekte olan ülke ekonomisine nasıl bir katkı sağladığını çevremizdeki insanlara aktarmak, insanlara geri dönüşüm atıklarını ayrıştırma bilinci kazandırmak, çöp olmayan atık maddelerin çöpe gitmesini önlemek.\n Sağlığa zarar veren çöplerin yararlı atıklardan ayrıştırılmasına katkıda bulunmak, çevremizdeki insanların ve okul arkadaşlarımızı geri dönüşüm hakkında daha duyarlı hale getirmek, belirli yaş aralığındaki bireyleri ne kadar geri dönüşüm yaptığı konusunda istatistiksel veriler çıkarmak\n ve bunları çevremize sunmak, doğal kaynakların korunması konusunda çevremizi bilinçlendirmek, çevremizdekilere geri dönüşüm bilinci kazandırmak, ülkemizdeki ham madde ihtiyacına katkıda bulunmak, insanları geri dönüşüm önemi konusunda bilgilendirmek, geri dönüşüm konusunda farkındalık yaratmak.";
    projenin_yonetimi11 = "Öncelikle Geri Dönüşüm farkındalığı konulu yerli ve yabancı anket sonuçlarını inceleyeceğiz.\n Edindiğimiz verileri gerekli çeviri ve düzenlemeleri yapıp sınıflandırdıktan sonra cevap yüzdeleri, yaş aralığı cinsiyet şeklinde rapor haline haline dönüştüreceğiz.\n Önceden tasarlanmış anketleri kaynak olarak kendi (Özgün) sorularımızı ekleyerek yeni bir anket hazırlayacak ve ağırlıkla Şişli olmak üzere İstanbul'un çeşitli yerlerinde rastgele insanlara sorularımızı soracağız.\n Anket çalışmasının ardından verileri analiz edecek ve şematize edeceğiz.\n Geri dönüştürülebilir atıkların nasıl değerlendirildiğini, tekrardan elimize ne şekilde döndüğünü, bu döngünün mikro ve makro düzeyde ekonomik katkılarını araştıracağız ve dosyalayacağız.\n Konuyla ilgili animasyon, belgesel, fotoğraf ve görsel kaynaklar ile yazılı kaynakları birleştirerek öğretici bir video oluşturacak, slogan belirleyecek ve afiş reklam çalışması yapacağız.\n Daha dikkat çekici olması için maskotlar yapacağız.\n Günümüzde gittikçe artmakta olanenerji ve ham madde kaynaklarının tükenmesinden dolayı kaçınılmaz bir faaliyet olan geri dönüşüm hakkında mümkün olduğunca büyük bir kitleye ulaşmak hedefindeyiz.\n Temel amacımız insanlara farkındalık kazandırmak olduğundan elde ettiğimiz istatiktiklerin yanı sıra geri dönüşüm yöntemlerinin de bilinmesi için insanları bilgi sahibi yapacağız.\n Okulumuzdaki arkadaşlarımıza sunumlar yapacağız.\n Geri dönüşümün önemini bildiği halde aktif bir parçası olamayan insanların sorunlarla göz ardı edilemeyeceğinden geri dönüşümü olabildiğince kolay hale gelmesi için çalışmalar yapacağız.\n Daha çok ve daha nitelikli geri dönüşüm kutuları konması için yetkililerle görüşmeler yapacağız.\n Çok miktardaki geri dönüştürülebilir artıkların (örneğin 10 kg) servis araçlarıyla evden tek seferde alınması için belediyelerde alt birimler oluşması için çalışmalar yapacağız.\n";
    sonuclar11 = "Yaptığımız anket sonuçları gösteriyor ki okulumuz öğrencileri geri dönüşüm konusunda cinsiyet fark etmeksizin aynı oranda bilinçlidir.\n Katılıyorum cevabı kişinin geri dönüşüm ve çevre kirliliği konusunda duyarlı olduğunu gösterirken katılmıyorum ve kararsızım seçenekleri kişinin duyarlı olmadığını ya da ilgilenmediğini göstermektedir.\n Kadın ve erkek oranları birebir aynı olduğuna göre: okulumuz öğrencilerinin %64'ü atıkların geri dönüştürmekte ve bu yolla ülke ekonomisine katkı sağlamaktadır.\n Bunun yanında %19'luk kesimin geri dönüştürmekte ve bu yolla ülke ekonomisine katkı sağlamaktadır.\n Bunun yanında %19'luk kesimin geri dönüştürmek için uğraşamadığını ve israfta olduğunu görüyoruz.\n %17'nin içindeki öğrencilerimiz geri dönüşüm konusunda kısmen bilinçli lduğu halde yorucu bulmaktadır.\n";
    oneriler11 = "Geri dönüşüm alışkanlıkların bireylere çocuk yaşta kazandırılması, bir rutin alışkanlık haline getirilmesi ve ülke ekonomisine katkısının öğretilmesi ebeveynleri görevi haline getirilmelidir.\n Daha çocuk yaştan alışverişe fileyle gitmeye alışmış, çöplerini ayıran, sokağında geri dönüşüm kutusu bulunan bireyler geri dönüşümün zor olmadığını kendi yedeğini pişirip, bulaşıklarını yıkamak kadar kolay ve elzem olduğunu iyi bilecektir.\n";
    }
};
 
