#include "namespace.h"
using namespace TUBITAK;

class proje19 {
	public:
		string baslik19;
		string kullanilan_materyaller19;
		string analiz_sonuclari19;
		string uygulanan_yontemler19;
		string soru19;
		string sonuclar19;
		string oneriler_beklentiler19;
	

		
		proje19() {
		baslik19="SUÇLULARLA EMPATİ \n";	
		kullanilan_materyaller19="Soru Kağıdı\n";
		analiz_sonuclari19="HÜKÜMLÜ VE TUTUKLULARA KARŞI , TOPLUM TARAFINDAN DIŞLAYIŞI VE ÖNYARGILI TUTUMVE DAVRANIŞLARA SERGİLENMEKTEDİR.\nBU DURUM DA 'SUÇLU' KİŞİLERİN TOPLUM HAYITINA YENİDEN KAZANDIRILMASININ ÖNÜNDE ENGEL OLUŞTURULMAKTADIR \n";
		uygulanan_yontemler19="LİTERATÜR TARAMA TÜMEVARIM EVREN - ÖRNEKLEM VERİ ANALİZİ\n";
		soru19=" 'SUÇLU'LARA KARŞI DUYULAN ÖNYARI NASIL KIRILABİLİR ? \nÖN YARGILARIN KIRILMASINDA KARŞIMIZA ÜÇ MODEL ÇIKMAKTADIR: \nDEFTER TUTMA MODELİ , DEĞİŞME MODELİ VE ALT KATEGORİ OLUŞTURMA MODELİ.\nBU ÇALIŞMADA ÖZELLİKLE DEĞİŞME . \nMODELİNİN ETKİLİ OLACAĞINI ÖNGÖRDÜK.\n'SUÇLU' BİREYLERİN HAYATI HİKAYELERİNİ AYRINTILI BİR ŞEKİLDE DİNLEYEN KİŞİLERİN BU ÖN YARGILARININ KIRILABİLECEĞİNİ DÜŞÜNDÜK.\nCEZAEVLERİNDE TUTUKLULARA YAPILAN MUAMELELER DE ÇALIŞMAMIZIN KONUSUDUR . \n549 MAHKUMA BİR PSİKOLOG , 986 MAHKUMA İSE BİR SOSYAL HİZMET UZMANI DÜŞMEKTEDİR. \n2010-1024 YILLARI ARASINDA 1200 KİŞİ CEZAEVLERİNDE HAYATINI KAYBETMİŞTİR.\nTÜRKİYE , MAHKUM NÜFUSU EN FAZLA OLAN ÜLKELER ARASINDA 9. SIRADA YER ALMAKTADIR.\n";
        sonuclar19="CEZAEVİNE GİRİP ÇIKMIŞ KİŞİLER HAKKINDAKİ ALGISINI ÖLÇTÜĞÜMÜZ KİŞİLERE SORULARIMI YÖNELTTİKTEN SONRA , YİNE AYNI KİŞİLERE , 33 YIL CEZAEVİNDE KALMIŞ  BİR KİŞİNİN HAPİSTEN ÇIKTIKTAN SONRAKİ YAŞAMINI ANLATTIĞI VİDEO İZLETİLMİŞTİR VE DÜŞÜNCELERİNİN DEĞİŞİP DEĞİŞMEDİĞİ YİNE KAĞIT ÜZERİNDE SORULMUŞTUR. \nBU ÇALIŞMA ESNASINDA GÖZLENEN DURUM KENDİLERİNE SORU YÖNELTİLEN KİŞİLERİN KENDİ ARALARINDA TARTIŞMALARI OLMUŞTUR. \nBU SORGULAMANIN DA BÜYÜK BİR KAZANIM OLDUĞUNU DÜŞÜNÜYORUZ.SORDUĞUMUZ SORULAR SAYESİNDE DAHA ÖNCEDEN 'SUÇLU' KİŞİLERE KARŞI ÖNYARGILI OLDUĞUNU SÖYLEYEN KİŞİLERDEN 25 KİŞİ , YÖNDE DEĞİŞTİĞİNİ BELİRMİŞTİR.\n";
        oneriler_beklentiler19="CEZAEVLERİNDEKİ KOŞULLARIN İNSAN HAKLARINA UYGUN BİR ŞEKİLDE REFORME EDİLMESİNİ , TUTUKLRIN YETERLİ PSİKOLOJİK DESTEK ALABİLMESİNİ , CEZAEVİNDEN ÇIKAN KİŞİLERİN İSTİHDAM EDİLMESİNİ , BARINMASININ SAĞLANMASINI ÖNERİYORUZ VE İNSANLARIN CEZAEVLERİNDEN ÇIKMIŞ KİŞİLERE KARŞI DUYMUŞ OLDUKLARI ÖN YARGILARININ KİŞİLER ARASI TANIŞIKLIKLAR , ORTAK YAŞANTILAR İLE KIRILABİLEĞİNİZİ DÜŞÜNÜYORUZ\n";

		}
};


