#include "namespace.h"
using namespace TUBITAK;

class proje19 {
	public:
		string baslik19;
		string kullanilan_materyaller19;
		string analiz_sonuclari19;
		string uygulanan_yontemler19;
		string soru19;
		string sonuclar19;
		string oneriler_beklentiler19;
	

		
		proje19() {
		baslik19="SUÇLULARLA EMPATÝ ";	
		kullanilan_materyaller19="Soru Kaðýdý";
		analiz_sonuclari19="HÜKÜMLÜ VE TUTUKLULARA KARÞI , TOPLUM TARAFINDAN DIÞLAYIÞI VE ÖNYARGILI TUTUMVE DAVRANIÞLARA SERGÝLENMEKTEDÝR. BU DURUM DA "SUÇLU" KÝÞÝLERÝN TOPLUM HAYITINA YENÝDEN KAZANDIRILMASININ ÖNÜNDE ENGEL OLUÞTURULMAKTADIR";
		uygulanan_yontemler19="LÝTERATÜR TARAMA TÜMEVARIM EVREN - ÖRNEKLEM VERÝ ANALÝZÝ";
		soru19=" "SUÇLU"LARA KARÞI DUYULAN ÖNYARI NASIL KIRILABÝLÝR ? ÖN YARGILARIN KIRILMASINDA KARÞIMIZA ÜÇ MODEL ÇIKMAKTADIR DEFTER TUTMA MODELÝ , DEÐÝÞME MODELÝ VE ALT KATEGORÝ OLUÞTURMA MODELÝ. BU ÇALIÞMADA ÖZELLÝKLE DEÐÝÞME . MODELÝNÝN ETKÝLÝ OLACAÐINI ÖNGÖRDÜK."SUÇLU" BÝREYLERÝN HAYATI HÝKAYELERÝNÝ AYRINTILI BÝR ÞEKÝLDE DÝNLEYEN KÝÞÝLERÝN BU ÖN YARGILARININ KIRILABÝLECEÐÝNÝ DÜÞÜNDÜK.CEZAEVLERÝNDE TUTUKLULARA YAPILAN MUAMELELER DE ÇALIÞMAMIZIN KONUSUDUR . 549 MAHKUMA BÝR PSÝKOLOG , 986 MAHKUMA ÝSE BÝR SOSYAL HÝZMET UZMANI DÜÞMEKTEDÝR. 2010-1024 YILLARI ARASINDA 1200 KÝÞÝ CEZAEVLERÝNDE HAYATINI KAYBETMÝÞTÝR.TÜRKÝYE , MAHKUM NÜFUSU EN FAZLA OLAN ÜLKELER ARASINDA 9. SIRADA YER ALMAKTADIR.";
        sonuclar19="CEZAEVÝNE GÝRÝP ÇIKMIÞ KÝÞÝLER HAKKINDAKÝ ALGISINI ÖLÇTÜÐÜMÜZ KÝÞÝLERE SORULARIMI YÖNELTTÝKTEN SONRA , YÝNE AYNI KÝÞÝLERE , 33 YIL CEZAEVÝNDE KALMIÞ  BÝR KÝÞÝNÝN HAPÝSTEN ÇIKTIKTAN SONRAKÝ YAÞAMINI ANLATTIÐI VÝDEO ÝZLETÝLMÝÞTÝR VE DÜÞÜNCELERRÝNÝN DEÐÝÞÝP DEÐÝÞMEDÝÐÝ YÝNE KAÐIT ÜZERÝNDE SORULMUÞTUR. BU ÇALIÞMA ESNASINDA GÖZLENEN DURUM KENDÝLERÝNE SORU YÖNELTÝLEN KÝÞÝLERÝN KENDÝ ARALARINDA TARTIÞMALARI OLMUÞTUR. BU SORGULAMANIN DA BÜYÜK BÝR KAZANIM OLDUÐUNU DÜÞÜNÜYORUZ.SORDUÐUMUZ SORULAR SAYESÝNDE DAHA ÖNCEDEN "SUÇLU" KÝÞÝLERE KARÞI ÖNYARGILI OLDUÐUNU SÖYLEYEN KÝÞÝLERDEN 25 KÝÞÝ , YÖNDE DEÐÝÞTÝÐÝNÝ BELÝRMÝÞTÝR.";
        oneriler_beklentiler19="CEZAEVLERÝNDEKÝ KOÞULLARIN ÝNSAN HAKLARINA UYGUN BÝR ÞEKÝLDE REFORME EDÝLMESÝNÝ , TUTUKLRIN YETERLÝ PSÝKOLOJÝK DESTEK ALABÝLMESÝNÝ , CEZAEVÝNDEN ÇIKAN KÝÞÝLERÝN ÝSTÝHDAM EDÝLMESÝNÝ , BARINMASININ SAÐLANMASINI ÖNERÝYORUZ VE ÝNSANLARIN CEZAEVLERÝNDEN ÇIKMIÞ KÝÞÝLERE KARÞI DUYMUÞ OLDUKLARI ÖN YARGILARININ KÝÞÝLER ARASI TANIÞIKLIKLAR , ORTAK YAÞANTILAR ÝLE KIRILABÝLEÐÝNÝZÝ DÜÞÜNÜYORUZ";

		}
};


