#include "namespace.h"

using namespace TUBITAK;

class proje11 {
    public:
    string baslik11;
    string materyaller11;
    string yontemler11;
    string ozet11;
    string amac11;
    string projenin_yonetimi11;
    string sonuclar11;
    string oneriler11;

    proje11() {
    baslik11 = "İLERİ DÜŞÜN GERİ DÖNÜŞTÜR\n";
    materyaller11 = "MATERYALLER\nTürkiye genelinde yapılan geri dönüşüm duyarlılığı anketleri incelendi.\nBu anketlerden soru örnekleri alınarak yeni bir anket oluşturuldu.\nArdından okul genelinde her sınıfta beş kız beş erkek öğrenci seçilerek öğrenci seçilerek uygulandı.\n";
    yontemler11 = "YÖNTEMLER\nDaha önceden Türkiye genelinde yapılmış olan anketler incelendi ve bilinen geri dönüşüm metodları araştırıldı.\nSonrasında okulum öğrencilerinin okul içinde ve özel yaşamlarında hangi geri dönüşüm metodlarını ne oranda kullanılabildiği araştırıldı.\nYaptığım anketler ile kadın ve erkek öğrencilerin geri dönüşümün ne kadar içinde olduklarını tespit etmeye çalıştık.\n";
    ozet11 = "ÖZET\nGeri dönüşüm kullanım dışım kalan geri dönüştürülebilir atık malzemelerin çeşitli geri dönüşüm yöntemleri ile ham madde olarak tekrar imalat süreçlerinde kazandırılmasıdır.\nGeri dönüşüm atıklarının nasıl değerlendiğini çevremizdeki insanlar biliyor mu?\nBu kazandırılma ülke ekonomisine ne kadar katkı sağlıyor?\nÜlke ekonomisi yanında insan yaşamı ve çevre içinde önemi nedir?\nAtıkların hepsini aynı yerde toplamak, ayrışmadan hepsini bir yerde biriktirmekle doğaya ve ülke ekonomisine zarar verdiğimizin farkında mıyız?\nBiz bu konuyu araştırarak, daha önce yapılmış anket ve istatistiksel verilerden yararlanarak insanları bilinçlendirmeyi amaçlıyoruz.\nSokaklarda çeşitli anketler yaparak her yaş aralığındaki insanların geri dönüşümün ekonomi ve birçok konu için ne kadar faydalı olduğu konusunda farkındalık yaratmak istiyoruz.\n";
    amac11 = "AMAÇ\nGeri dönüşümün gelişmekte olan ülke ekonomisine nasıl bir katkı sağladığını çevremizdeki insanlara aktarmak, insanlara geri dönüşüm atıklarını ayrıştırma bilinci kazandırmak, çöp olmayan atık maddelerin çöpe gitmesini önlemek.\nSağlığa zarar veren çöplerin yararlı atıklardan ayrıştırılmasına katkıda bulunmak, çevremizdeki insanların ve okul arkadaşlarımızı geri dönüşüm hakkında daha duyarlı hale getirmek, belirli yaş aralığındaki bireyleri ne kadar geri dönüşüm yaptığı konusunda istatistiksel veriler çıkarmakve bunları çevremize sunmak, doğal kaynakların korunması konusunda çevremizi bilinçlendirmek, çevremizdekilere geri dönüşüm bilinci kazandırmak, ülkemizdeki ham madde ihtiyacına katkıda bulunmak, insanları geri dönüşüm önemi konusunda bilgilendirmek, geri dönüşüm konusunda farkındalık yaratmak.\n";
    projenin_yonetimi11 = "PROJENİN YÖNTEMLERİ\nÖncelikle Geri Dönüşüm farkındalığı konulu yerli ve yabancı anket sonuçlarını inceleyeceğiz.\nEdindiğimiz verileri gerekli çeviri ve düzenlemeleri yapıp sınıflandırdıktan sonra cevap yüzdeleri, yaş aralığı cinsiyet şeklinde rapor haline haline dönüştüreceğiz.\nÖnceden tasarlanmış anketleri kaynak olarak kendi (Özgün) sorularımızı ekleyerek yeni bir anket hazırlayacak ve ağırlıkla Şişli olmak üzere İstanbul'un çeşitli yerlerinde rastgele insanlara sorularımızı soracağız.\nAnket çalışmasının ardından verileri analiz edecek ve şematize edeceğiz.\nGeri dönüştürülebilir atıkların nasıl değerlendirildiğini, tekrardan elimize ne şekilde döndüğünü, bu döngünün mikro ve makro düzeyde ekonomik katkılarını araştıracağız ve dosyalayacağız.\nKonuyla ilgili animasyon, belgesel, fotoğraf ve görsel kaynaklar ile yazılı kaynakları birleştirerek öğretici bir video oluşturacak, slogan belirleyecek ve afiş reklam çalışması yapacağız.\nDaha dikkat çekici olması için maskotlar yapacağız.\nGünümüzde gittikçe artmakta olanenerji ve ham madde kaynaklarının tükenmesinden dolayı kaçınılmaz bir faaliyet olan geri dönüşüm hakkında mümkün olduğunca büyük bir kitleye ulaşmak hedefindeyiz.\nTemel amacımız insanlara farkındalık kazandırmak olduğundan elde ettiğimiz istatiktiklerin yanı sıra geri dönüşüm yöntemlerinin de bilinmesi için insanları bilgi sahibi yapacağız.\nOkulumuzdaki arkadaşlarımıza sunumlar yapacağız.\nGeri dönüşümün önemini bildiği halde aktif bir parçası olamayan insanların sorunlarla göz ardı edilemeyeceğinden geri dönüşümü olabildiğince kolay hale gelmesi için çalışmalar yapacağız.\nDaha çok ve daha nitelikli geri dönüşüm kutuları konması için yetkililerle görüşmeler yapacağız.\nÇok miktardaki geri dönüştürülebilir artıkların (örneğin 10 kg) servis araçlarıyla evden tek seferde alınması için belediyelerde alt birimler oluşması için çalışmalar yapacağız.\n";
    sonuclar11 = "SONUÇLAR\nYaptığımız anket sonuçları gösteriyor ki okulumuz öğrencileri geri dönüşüm konusunda cinsiyet fark etmeksizin aynı oranda bilinçlidir.\nKatılıyorum cevabı kişinin geri dönüşüm ve çevre kirliliği konusunda duyarlı olduğunu gösterirken katılmıyorum ve kararsızım seçenekleri kişinin duyarlı olmadığını ya da ilgilenmediğini göstermektedir.\nKadın ve erkek oranları birebir aynı olduğuna göre: okulumuz öğrencilerinin %64'ü atıkların geri dönüştürmekte ve bu yolla ülke ekonomisine katkı sağlamaktadır.\nBunun yanında %19'luk kesimin geri dönüştürmekte ve bu yolla ülke ekonomisine katkı sağlamaktadır.\nBunun yanında %19'luk kesimin geri dönüştürmek için uğraşamadığını ve israfta olduğunu görüyoruz.\n%17'nin içindeki öğrencilerimiz geri dönüşüm konusunda kısmen bilinçli lduğu halde yorucu bulmaktadır.\n";
    oneriler11 = "ÖZETLER\nGeri dönüşüm alışkanlıkların bireylere çocuk yaşta kazandırılması, bir rutin alışkanlık haline getirilmesi ve ülke ekonomisine katkısının öğretilmesi ebeveynleri görevi haline getirilmelidir.\nDaha çocuk yaştan alışverişe fileyle gitmeye alışmış, çöplerini ayıran, sokağında geri dönüşüm kutusu bulunan bireyler geri dönüşümün zor olmadığını kendi yedeğini pişirip, bulaşıklarını yıkamak kadar kolay ve elzem olduğunu iyi bilecektir.\n";
    }
};
 
