#include "Kaynak_Dosyalar/namespace.h"

using namespace TUBITAK;

class TUBITAK::proje14 {
public:
    QString baslik14;
    QString metin14;

    proje14() {
        baslik14 = "KÜRESEL ISINMA VE İKLİM DEĞİŞİKLİKLERİ KONUSUNDA FARKINDALIK OLUŞTURUYORUZ";
        metin14 = "<br><br>Günümüzde küresel ısınmanın etkileri iyice artmaya başladı.<br>İnsanlar bu konuda yeterli bilgi düzeyine sahip değil. <br>Biz de bu konuda insanları bilgilendirecek bir farkındalık oluşturmaya çalıştık.<br>Küresel ısınmaya neden olan karbon salınımı konusunda 'karbon ayak izi' adı altında insanları bilgilendirmeye yönelik çalışmalar yaptık.<br><br>Hipotezimiz:<br><br> Okulumuzdaki öğrenciler karbon ayak izi konusunda bilinçli değildir.<br><br>SORULAR<br><br>Karbon ayak izi nedir?<br>Karbon ayak izimizi azaltmak için neler yapmalıyız?<br>Karbon ayak izinin Dünyamıza etkileri nelerdir?<br>Karbon ayak izini küçültmez isek ileride hangi sorunlarla karşı karşıya gelebiliriz? <br>Yukarıdaki sorulara cevap bulabilmek için araştırmalar yaptık.<br>Bu konuda çeşitli çalışmalar( İstatistiksel grafikler, afişler, röportajlar) yaparak ve çeşitli seminerler vererek öğrencileri bilinçlendirmiş olduk.<br>Atmosferdeki karbon etkisini göstermek amacıyla, karbon salımının artmasıyla oluşabilecek sonuçları gösterecek bir deney yapacağız.<br>Deneyimizin sonucunda karbondioksit gazı verilen kaptaki buzun daha çabuk eridiği  gözlemlendi. <br><br>MALZEMELER<br><br>PLASTİK KAP<br>BUZ KALIBI <br>STREÇ FİLM<br>KARBONDİOKSİT<br> <br><br>AMAÇ<br><br> Günümüzde küresel ısınmanın etkileri iyice artmaya başladı.<br>İnsanlar bu konuda yeterli bilinç düzeyine sahip değil.<br>Biz de bu konuda insanları bilgilendirerek bir farkındalık oluşturmaya çalıştık.<br>Küresel ısınmaya neden olan karbon salınımı konusunda.<br>'Karbon ayak izi'adı altında insanları bilgilendirmeye yönelik çalışmalar yaptık.<br>Karbon ayak izi konusunda bilinç düzeyini ölçmek için röportajlar yaptık.<br>Öncelikle okulumuzdaki arkadaşlarımıza yapacağımız röportajlarla sınıf düzeyinde karbon ayak izi farkındalığını görmüş olacağız.<br>Daha sonra Şişli ilçesinde farklı sosyal gruplar üzerinde röportajlar yapacağız.<br>Bu sonuçları daha iyi görebilmek için istatistik çalışmaları yaparak grafikler oluşturacağız.<br>Her sınıf düzeyinde bir öğrenci ile röportaj yapacağız.<br>Şişli ilçesinde ise belli mahallelerden insanlarla röportaj yapacağız.<br>Karbon ayak izi konusunda bilinç düzeylerini tespit ettikten sonra insanların bu konudaki farkındalığını artırmak için çeşitli etkinlikler düzenleyeceğiz.<br>Okulumuzda öğrenci arkadaşlarımızın ve Şişli İlçesi sınırları içinde yaşayan insanların karbon ayak izi bilgi düzeyini artırmak için tanıtım afişleri hazırlayacağız.<br>Hazırladığımız afişlerimizde karbon ayak izi konusundaki bilinç düzeyini açıklayan istatistikler, dikkat çekici grafikler kullandık.<br>Hazırladığımız afişleri okulumuzun belli başlı  bölgelerinde sergiledik.<br> Okulumuzda vereceğimiz seminerlerle küresel ısınma ve karbon ayak izi konusunda arkadaşlarımızı bilgilendirdik.<br>Karbon salınımının etkisini gösteren bir deney çalışması yapacağız.<br><br>HİPOTEZİMİZ<br><br>OKULUMUZ ÖĞRENCİLERİ KARBON AYAK İZİNİ BİLMİYOR<br>";
    }
};
