#include "Kaynak_Dosyalar/namespace.h"

using namespace TUBITAK;

class proje14 {
public:
    QString baslik14;
    QString metin14;

    proje14() {
        baslik14 = "KÜRESEL ISINMA VE İKLİM DEĞİŞİKLİKLERİ KONUSUNDA FARKINDALIK OLUŞTURUYORUZ";
        metin14 = "Günümüzde küresel ısınmanın etkileri iyice artmaya başladı. \nİnsanlar bu konuda yeterli bilgi düzeyine sahip değil. \nBiz de bu konuda insanları bilgilendirecek bir farkındalık oluşturmaya çalıştık. \nKüresel ısınmaya neden olan karbon salınımı konusunda 'karbon ayak izi' adı altında insanları bilgilendirmeye yönelik çalışmalar yaptık. \nHipotezimiz: Okulumuzdaki öğrenciler karbon ayak izi konusunda bilinçli değildir. \nKarbon ayak izi nedir? \nKarbon ayak izimizi azaltmak için neler yapmalıyız? \nKarbon ayak izinin Dünyamıza etkileri nelerdir? \nKarbon ayak izini küçültmez isek ileride hangi sorunlarla karşı karşıya gelebiliriz? \nYukarıdaki sorulara cevap bulabilmek için araştırmalar yaptık. \nBu konuda çeşitli çalışmalar( İstatistiksel grafikler, afişler, röportajlar) yaparak ve çeşitli seminerler vererek öğrencileri bilinçlendirmiş olduk.\nAtmosferdeki karbon etkisini göstermek amacıyla, karbon salımının artmasıyla oluşabilecek sonuçları gösterecek bir deney yapacağız.\nDeneyimizin sonucunda karbondioksit gazı verilen kaptaki buzun daha çabuk eridiği  gözlemlendi.\nPLASTİK KAP \nBUZ KALIBI \nSTREÇ FİLM \nKARBONDİOKSİT\nGünümüzde küresel ısınmanın etkileri iyice artmaya başladı. \nİnsanlar bu konuda yeterli bilinç düzeyine sahip değil. \nBiz de bu konuda insanları bilgilendirerek bir farkındalık oluşturmaya çalıştık. \nKüresel ısınmaya neden olan karbon salınımı konusunda. \n'Karbon ayak izi'adı altında insanları bilgilendirmeye yönelik çalışmalar yaptık. \nKarbon ayak izi konusunda bilinç düzeyini ölçmek için röportajlar yaptık.\nÖncelikle okulumuzdaki arkadaşlarımıza yapacağımız röportajlarla sınıf düzeyinde karbon ayak izi farkındalığını görmüş olacağız.\nDaha sonra Şişli ilçesinde farklı sosyal gruplar üzerinde röportajlar yapacağız. \nBu sonuçları daha iyi görebilmek için istatistik çalışmaları yaparak grafikler oluşturacağız. \nHer sınıf düzeyinde bir öğrenci ile röportaj yapacağız. \nŞişli ilçesinde ise belli mahallelerden insanlarla röportaj yapacağız. \nKarbon ayak izi konusunda bilinç düzeylerini tespit ettikten sonra insanların bu konudaki farkındalığını artırmak için çeşitli etkinlikler düzenleyeceğiz. \nOkulumuzda öğrenci arkadaşlarımızın ve Şişli İlçesi sınırları içinde yaşayan insanların karbon ayak izi bilgi düzeyini artırmak için tanıtım afişleri hazırlayacağız. \nHazırladığımız afişlerimizde karbon ayak izi konusundaki bilinç düzeyini açıklayan istatistikler, dikkat çekici grafikler kullandık. \nHazırladığımız afişleri okulumuzun belli başlı  bölgelerinde sergiledik. Okulumuzda vereceğimiz seminerlerle küresel ısınma ve karbon ayak izi konusunda arkadaşlarımızı bilgilendirdik. \nKarbon salınımının etkisini gösteren bir deney çalışması yapacağız.\nOKULUMUZ ÖĞRENCİLERİ KARBON AYAK İZİNİ BİLMİYOR\n";
    }
};
