#include "Kaynak_Dosyalar/namespace.h"
using namespace TUBITAK;

class TUBITAK::proje11 {
	public:
        QString baslik11;
        QString metin11;

        proje11() {
        baslik11="SUÇLULARLA EMPATİ";
        metin11 ="KULLANILAN MATERYALLER<br><br>Soru Kağıdı<br>ANALİZ SONUÇLARI<br><br>HÜKÜMLÜ VE TUTUKLULARA KARŞI , TOPLUM TARAFINDAN DIŞLAYIŞI VE ÖNYARGILI TUTUM VE DAVRANIŞLARA SERGİLENMEKTEDİR.<br>BU DURUM DA 'SUÇLU' KİŞİLERİN TOPLUM HAYITINA YENİDEN KAZANDIRILMASININ ÖNÜNDE ENGEL OLUŞTURULMAKTADIR <br>UYGULANAN YÖNTEMLER<br>LİTERATÜR TARAMA TÜMEVARIM EVREN - ÖRNEKLEM VERİ ANALİZİ<br>SORU <br>'SUÇLU'LARA KARŞI DUYULAN ÖNYARI NASIL KIRILABİLİR ? <br>ÖN YARGILARIN KIRILMASINDA KARŞIMIZA ÜÇ MODEL ÇIKMAKTADIR: <br>DEFTER TUTMA MODELİ , DEĞİŞME MODELİ VE ALT KATEGORİ OLUŞTURMA MODELİ.<br>BU ÇALIŞMADA ÖZELLİKLE DEĞİŞME . <br>MODELİNİN ETKİLİ OLACAĞINI ÖNGÖRDÜK.<br>'SUÇLU' BİREYLERİN HAYATI HİKAYELERİNİ AYRINTILI BİR ŞEKİLDE DİNLEYEN KİŞİLERİN BU ÖN YARGILARININ KIRILABİLECEĞİNİ DÜŞÜNDÜK.<br>CEZAEVLERİNDE TUTUKLULARA YAPILAN MUAMELELER DE ÇALIŞMAMIZIN KONUSUDUR .<br>549 MAHKUMA BİR PSİKOLOG , 986 MAHKUMA İSE BİR SOSYAL HİZMET UZMANI DÜŞMEKTEDİR. <br>2010-1024 YILLARI ARASINDA 1200 KİŞİ CEZAEVLERİNDE HAYATINI KAYBETMİŞTİR.<br>TÜRKİYE , MAHKUM NÜFUSU EN FAZLA OLAN ÜLKELER ARASINDA 9. SIRADA YER ALMAKTADIR.<br>SONUÇLAR<br><br>CEZAEVİNE GİRİP ÇIKMIŞ KİŞİLER HAKKINDAKİ ALGISINI ÖLÇTÜĞÜMÜZ KİŞİLERE SORULARIMI YÖNELTTİKTEN SONRA , YİNE AYNI KİŞİLERE , 33 YIL CEZAEVİNDE KALMIŞ  BİR KİŞİNİN HAPİSTEN ÇIKTIKTAN SONRAKİ YAŞAMINI ANLATTIĞI VİDEO İZLETİLMİŞTİR VE DÜŞÜNCELERİNİN DEĞİŞİP DEĞİŞMEDİĞİ YİNE KAĞIT ÜZERİNDE SORULMUŞTUR.<br>BU ÇALIŞMA ESNASINDA GÖZLENEN DURUM KENDİLERİNE SORU YÖNELTİLEN KİŞİLERİN KENDİ ARALARINDA TARTIŞMALARI OLMUŞTUR.<br>BU SORGULAMANIN DA BÜYÜK BİR KAZANIM OLDUĞUNU DÜŞÜNÜYORUZ.SORDUĞUMUZ SORULAR SAYESİNDE DAHA ÖNCEDEN 'SUÇLU' KİŞİLERE KARŞI ÖNYARGILI OLDUĞUNU SÖYLEYEN KİŞİLERDEN 25 KİŞİ , YÖNDE DEĞİŞTİĞİNİ BELİRMİŞTİR.<br>ÖNERİLER VE BEKLENTİLER<br><br>CEZAEVLERİNDEKİ KOŞULLARIN İNSAN HAKLARINA UYGUN BİR ŞEKİLDE REFORME EDİLMESİNİ , TUTUKLRIN YETERLİ PSİKOLOJİK DESTEK ALABİLMESİNİ , CEZAEVİNDEN ÇIKAN KİŞİLERİN İSTİHDAM EDİLMESİNİ , BARINMASININ SAĞLANMASINI ÖNERİYORUZ VE İNSANLARIN CEZAEVLERİNDEN ÇIKMIŞ KİŞİLERE KARŞI DUYMUŞ OLDUKLARI ÖN YARGILARININ KİŞİLER ARASI TANIŞIKLIKLAR , ORTAK YAŞANTILAR İLE KIRILABİLEĞİNİZİ DÜŞÜNÜYORUZ<br>";
		}
};
