#include "Kaynak_Dosyalar/namespace.h"

using namespace TUBITAK;

class TUBITAK::proje13 {
	public:
        QString baslik13;
        QString metin13;
     	QString yapan13;
    proje13() {
    baslik13 = "TÜBİTAK 4006 PROJESİ KOMPOST OLUŞUMUNDA ŞARTLARIN ETKİSİ";
    metin13 = "KULLANILAN MATERYALLER<br><br>Doğal atıklar(Sebze ve Meyve Atıkları), Kazma, Kürek, Renksiz, Karton <br><br>PROJE YÖNTEMİ<br><br>Proje kapsamında Permakültür Tarım yapabilmek için kompost hazırladık.<br>Hazırladığımız kompostu üç alanda yaptık.<br>Bunlar Varilde kompostta Toprağın içinde kompost Toprak yüzeyinde(dışarıda) kompost Bu üç kompost yapımı içim süre ve eşit miktarda organik atık kullandık.<br>Kompost yapımı ve permakültür tarım için okulumuzun kapalı spor salonunun arkasındaki boş arsayı kullandık.<br>Öncelikle kendi evlerimizdeki evsel gıda atıklarımızı depolayıp okula getirdik.<br>Bu atıkların içinde pişmiş yemek, ekmek, portakal-limon kabuğu ve soğan kabuğu yoktu.<br>Meyve-sebze atıkları, çay-kahve artığı, karton, ağaç yaprakları kompost yapımı için  uygun atıklardır.<br>Bu atıkları gerek evimizden getirmek suretiyle gerekse okul kantini ve öğretmenlerimizin kullandığı mutfaktan temin ettik.<br>Ağaç yapraklarını ise okulumuz bahçesindeki ağaçların düşen yapraklarını toplayarak temin ettik.<br>Kompost hazırlama sürecinde öncelikle karton atıklarımızı kompostumuzun en alt kısmına yerleştirdik.<br>Karton atıklarının üzerine gıda artıklarını, onun üzerine ağaç yapraklarını en üste ise çay ve kahve atıklarını ekledik.<br>Tabakalar halinde koyduğumuz bu artıkları iki günde bir karıştırmaya çalıştık.<br>Evlerimizden getirdiğimiz veya okuldan temin ettiğimiz artık maddeleri kompostumuzun üzerine ekledik.<br>Her eklemeden sonra kompostumuzu karıştırdık.<br>Karıştırma sırasında kompostumuza su da ekledik.<br>Yaklaşık üç ay boyunca eklemelerle hazırladığımız kompostlarımızın yapım sürecini fotoğraf çekmek suretiyle gözlemleyerek kayıt altına aldık.<br>Üç ayrı alanda kompost hazırladığımız için bunları üç farklı yarım yatağında deneyeceğiz.<br><br>SORU<br><br>Kompost oluşumunda ortam ve dış faktörlerin etkisi fazla mıdır?<br><br>HİPOTEZ<br><br>Kompost hazırlanmasında ve kompostun en hızlı  ve en verimli oluşturulacağı hakkında bilgi edinmek.<br><br>KONU ARAŞTIRMASI<br><br>Günlük hayatta organik atıklarımızı nasıl verimli hale getirebiliriz ve tarım için kullanabiliriz, bu sayede organik tarım konusunda da bilinçlenmiş olacağız.<br><br>ANALİZ<br><br>Kompostların yapım sürecinde toprağın içinde yaptığımız kompostun daha hızlı geliştiğini gözlemledik.<br>En yavaş ise yer üstünde olanıydı.<br>Toprakta canlı organizmanın(solucan,bakteri vb.)daha çok olmasından dolayı diğerlerine göre toprağın içindeki kompostumuz daha hızlı gelişmiştir.<br>Varildeki kompostumuza toprak altındaki canlı organizmalar ulaşamacağından yer altındakine göre daha yavaş geliştiğini gözlemledik.<br>Yer üstündeki kompostumuz ise açık alanda olduğu için ısısını ve nemini koruyamadı.<br>Nem ve sıcaklık enzimlerin ve canlı organizmaların yaşayabilmesi için gerek bir etken olduğundan diğer kompostlarımıza göre geride kaldı.<br>";
    yapan13= "<br><br>YAPANLAR(9/A)<br><br>Tunç ALPARTUN<br>Ulvi KESİM<br>Gökmen ERÇAYAN<br> Ali CONTARLI<br> Sude (10/B)<br> Hatice(10/B)<br>"	;
    }
};
